name: personal_finance_helper
description: Приложение для учета финансов самозанятых

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  syncfusion_flutter_charts: ^29.2.7 # Обновите до последней версии
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter:
    sdk: flutter
  provider: ^6.0.5 # Добавьте эту строку
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true